### ISSUE TITLE
CameraWorkbench Startup on CentOS 

### ISSUE THREAD

**Issue by jpagliaccio** [node-/CameraWorkbench#2]
Edit: I saw the proper syntax in the code so now with 

**# python ./CameraWorkbench.py --amscope --webcam  2** 

Gtk-Message: 13:21:33.323: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "./CameraWorkbench.py", line 263, in <module>
    main()
  File "./CameraWorkbench.py", line 253, in main
    cams = [CameraManager(Camera(device, fullRes=True), device) for device in args.devices]
  File "/home/jpagliaccio/Nessi_Project/CameraWorkbench-master/camera.py", line 167, in __init__
    self.capture.set(cv2.CAP_PROP_FRAME_WIDTH, 1920.0)
AttributeError: 'module' object has no attribute 'CAP_PROP_FRAME_WIDTH'

Any Ideas? 
Thanks,
Joe

----------------------

Hey Jake:

I am trying to start CamCameraWorkbench.py on CentOS for the first time. Its CentOS 7, python 2.7.5, I have everything installed (PIL and Qt) and I am using a AMScope MU1403 USB 3.0 camera. 

dmesg gives me: 

4309.256067] usb 4-1: new SuperSpeed USB device number 2 using xhci_hcd
[ 4309.267824] usb 4-1: LPM exit latency is zeroed, disabling LPM.
[ 4309.268531] usb 4-1: New USB device found, idVendor=0547, idProduct=3b14
[ 4309.268543] usb 4-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 4309.268551] usb 4-1: Product: USB3.0 Camera
[ 4309.268558] usb 4-1: Manufacturer: TP

When I run the startup command I get this: 

# python ./CameraWorkbench.py --amscope --webcam devices 2
usage: CameraWorkbench.py [-h] [--amscope] [--webcam] devices [devices ...]
CameraWorkbench.py: error: argument devices: invalid int value: 'devices'

How should I ne specifiying the device? 

Thanks for the help. I am eager to get it going. 

Joe

**Comment by node-** [comment]
The version of CV2 is out of date. I recommend upgrading to the newest version of Toupcam as well - they have python bindings now. I have no plan to update this UI with the new bindings however.
